on: 
     push:
        branches: [ "main" ]
name: 🚀 Deploy website on push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: ${{ secrets.W1_HOST }}
          repository_root: 'public_html/PruebaThree'
          port: '2083' # Optional. Don't change it unless you know what you're doing
          username: ${{ secrets.W1_USERNAME }} # Your cPanel username
          branch: main
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"




 


